blueprint:
  name: ISS card Blueprint
  description: International Space Station card by Michel Jourdain
  version: "1.0"
  type: card
  
  custom_cards:
    - vertical-stack-in-card

  input:
  
    01_translate_number_of_peoples:
       name: Translate Number of people on board
       description: Translate Number of people on board in your language
       type: text-field
       
    02_translate_next_rise:
       name: Translate next rise
       description: Translate next rise in your language
       type: text-field
       
    03_translate_longitude:
       name: Translate longitude
       description: Translate longitude in your language
       type: text-field
       
    04_translate_latitude:
       name: Translate latitude
       description: Translate latitude in your language
       type: text-field

    05_disable_dark_mode:
       name: Disable dark mode
       description: Disable dark mode for map
       type: checkbox

card:

  type: custom:dwains-flexbox-card
  items_classes: 'col-xs-12'
  cards:

     - type: custom:vertical-stack-in-card
       cards:
  
         - type: entities
           title: ISS
           entities:
             - entity: sensor.international_space_station_peoples_in
               name: $01_translate_number_of_peoples$
             - entity: sensor.international_space_station_next_rise
               name: $02_translate_next_rise$
             - entity: sensor.international_space_station_longitude
               name: $03_translate_longitude$
             - entity: sensor.international_space_station_latitude
               name: $04_translate_latitude$
           tap_action:
             action: none
           hold_action:
             action: none

         - type: map
           entities:
              - entity: binary_sensor.iss
           dark_mode: $05_disable_dark_mode$
           aspect_ratio: 50%
           hours_to_show: 2
           default_zoom: 1.5
