blueprint:
  custom_cards:
  - button-card
  - mini-graph-card
  description: AdGuard Page by mase
  name: AdGuard Page Blueprint
  type: page
  version: '1.0'
card:
  type: custom:dwains-flexbox-card
  items_classes: 'col-xs-12 col-sm-6 col-md-6 col-lg-6'
  cards:
    - type: custom:mini-graph-card
      entities:
        - entity: sensor.adguard_dns_queries
          name: DNS Queries
    - type: custom:mini-graph-card
      entities:
        - entity: sensor.adguard_dns_queries_blocked
          name: DNS Queries blocked
    - type: custom:button-card
      entity: switch.adguard_protection
      show_name: true
      show_icon: true
      show_state: true
      show_label: false
      show_last_changed: false
      tap_action:
        haptic: light
        action: toggle
      state:
        - value: 'on'
          icon: fas:toggle-on
        - value: 'off'
          icon: fas:toggle-off
          styles:
            icon:
              - color: '#6c6c75'
      styles:
        grid:
          - grid-template-areas: '"i n""i s"'
          - grid-template-columns: 30% 70%
          - grid-template-rows: min-content
        card:
          - border-radius: 12px
          - margin-bottom: 0px
          - padding-top: 14px
          - padding-bottom: 14px
        icon:
          - width: 55%
          - color: var(--primary-color)
        img_cell:
          - width: 45px
          - height: 45px
          - border-radius: 100%
          - background: var(--secondary-background-color)
        name:
          - color: var(--primary-text-color)
          - justify-self: start
          - font-size: 15px
          - align-self: center
        state:
          - justify-self: start
          - align-self: left
          - font-size: 13px
          - color: var(--disabled-text-color)
        label:
          - justify-self: start
          - align-self: left
          - font-size: 12px
          - color: var(--disabled-text-color)
    - type: custom:button-card
      entity: switch.adguard_filtering
      show_name: true
      show_icon: true
      show_state: true
      show_label: false
      show_last_changed: false
      tap_action:
        haptic: light
        action: toggle
      state:
        - value: 'on'
          icon: fas:toggle-on
        - value: 'off'
          icon: fas:toggle-off
          styles:
            icon:
              - color: '#6c6c75'
      styles:
        grid:
          - grid-template-areas: '"i n""i s"'
          - grid-template-columns: 30% 70%
          - grid-template-rows: min-content
        card:
          - border-radius: 12px
          - margin-bottom: 0px
          - padding-top: 14px
          - padding-bottom: 14px
        icon:
          - width: 55%
          - color: var(--primary-color)
        img_cell:
          - width: 45px
          - height: 45px
          - border-radius: 100%
          - background: var(--secondary-background-color)
        name:
          - color: var(--primary-text-color)
          - justify-self: start
          - font-size: 15px
          - align-self: center
        state:
          - justify-self: start
          - align-self: left
          - font-size: 13px
          - color: var(--disabled-text-color)
        label:
          - justify-self: start
          - align-self: left
          - font-size: 12px
          - color: var(--disabled-text-color)
